server/src/main/java/de/belmega/biohazard/server/persistence/entities/WorldSimulationEntity.java
package de.belmega.biohazard.server.persistence.entities;

import de.belmega.biohazard.server.persistence.state.WorldState;

import javax.persistence.*;
import java.sql.Timestamp;

/**
 * The world entity contains meta data about the specific game world,
 * that are used to manage the world, but not part of the simulation.
 * It references a WorldState entity that represents the world simulation.
 */
@Entity
public class WorldSimulationEntity {


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    private String name;

    private Timestamp creationDate;

    @OneToOne(cascade = CascadeType.ALL)
    private WorldState state;

    public WorldSimulationEntity() {
        this.creationDate = new Timestamp(System.currentTimeMillis());
    }

    public WorldSimulationEntity(String name) {
        this.name = name;
        this.creationDate = new Timestamp(System.currentTimeMillis());
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Timestamp getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Timestamp creationDate) {
        this.creationDate = creationDate;
    }

    public WorldState getWorldState() {
        return state;
    }

    public void setWorldState(WorldState state) {
        this.state = state;
    }
}

server/src/main/java/de/belmega/biohazard/server/jsf/CountryDetailsBean.java
package de.belmega.biohazard.server.jsf;

import de.belmega.biohazard.server.ejb.CountryDAO;
import de.belmega.biohazard.server.persistence.state.CountryState;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.inject.Inject;

@ManagedBean
@RequestScoped
public class CountryDetailsBean {
    private long countryId;
    private CountryState country;

    @Inject
    private CountryDAO countryDAO;

    public long getCountryId() {
        return countryId;
    }

    public void setCountryId(long countryId) {
        this.countryId = countryId;
    }

    public CountryState getCountry() {
        return country;
    }

    public void setCountry(CountryState country) {
        this.country = country;
    }

    public void loadCountry() {
        country = countryDAO.findCountry(countryId);
    }
}

server/src/main/java/de/belmega/biohazard/server/jsf/CreateWorldBean.java
package de.belmega.biohazard.server.jsf;

import de.belmega.biohazard.server.ejb.WorldDAO;
import de.belmega.biohazard.server.persistence.entities.WorldSimulationEntity;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.inject.Inject;

/**
 * @author tbelmega on 04.12.2016.
 */
@ManagedBean
@SessionScoped
public class CreateWorldBean {
    @Inject
    WorldDAO worldDAO;
    private WorldSimulationEntity worldSimulationEntity;

    public String destroyWorldEntity() {
        worldSimulationEntity = null;
        return "index";
    }

    public WorldSimulationEntity getWorldSimulationEntity() {
        if (worldSimulationEntity == null)
            worldSimulationEntity = new WorldSimulationEntity();
        return worldSimulationEntity;
    }

    public void setWorldSimulationEntity(WorldSimulationEntity worldSimulationEntity) {
        this.worldSimulationEntity = worldSimulationEntity;
    }

    public String submit() {
        worldDAO.saveWorld(getWorldSimulationEntity());
        worldSimulationEntity = null;
        return "index";
    }
}

server/src/main/java/de/belmega/biohazard/server/jsf/PrintWorldReportBean.java
package de.belmega.biohazard.server.jsf;

import de.belmega.biohazard.server.ejb.WorldDAO;
import de.belmega.biohazard.server.persistence.entities.WorldSimulationEntity;
import de.belmega.biohazard.server.printing.PrintWorldList;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;

@ManagedBean
@RequestScoped
public class PrintWorldReportBean {

    @Inject
    WorldDAO dao;

    private long worldId;

    public void btnPrintClick() throws IOException {
        FacesContext facesContext = FacesContext.getCurrentInstance();
        ExternalContext externalContext = facesContext.getExternalContext();
        HttpServletResponse response = (HttpServletResponse) externalContext.getResponse();

        response.reset(); // Some JSF component library or some Filter might have set some headers in the buffer beforehand. We want to get rid of them, else it may collide.
        response.setContentType("application/pdf"); // Check http://www.iana.org/assignments/media-types for all types. Use if necessary ServletContext#getMimeType() for auto-detection based on filename.
        response.setHeader("Content-disposition", "attachment; filename=\"name.pdf\""); // The Save As popup magic is done here. You can give it any filename you want, this only won't work in MSIE, it will use current request URL as filename instead.

        OutputStream output = response.getOutputStream();

        fillResponseOutput(output);

        facesContext.responseComplete();
    }

    private void fillResponseOutput(OutputStream output) throws IOException {
        WorldSimulationEntity world = dao.findWorld(worldId);

        String fileName = "/test2.jasper";
        InputStream inputStream = getClass().getResourceAsStream(fileName);

        Map<String, Object> map = new HashMap<>();

        JRBeanCollectionDataSource dataSource = PrintWorldList.createDataSource();
        try {
            JasperPrint print = JasperFillManager.fillReport(
                    inputStream,
                    map,
                    dataSource);
            JasperExportManager.exportReportToPdfStream(print, output);
        } catch (JRException e) {

            e.printStackTrace();
        } finally {
            output.close();
        }
    }

    public long getWorldId() {
        return worldId;
    }

    public void setWorldId(long worldId) {
        this.worldId = worldId;
    }
}

server/src/main/java/de/belmega/biohazard/server/jsf/WorldDetailsBean.java
package de.belmega.biohazard.server.jsf;

import de.belmega.biohazard.core.world.World;
import de.belmega.biohazard.server.ejb.WorldDAO;
import de.belmega.biohazard.server.ejb.WorldRunStatus;
import de.belmega.biohazard.server.persistence.entities.WorldSimulationEntity;
import de.belmega.biohazard.server.persistence.state.ContinentState;
import de.belmega.biohazard.server.persistence.state.CountryState;
import de.belmega.biohazard.server.persistence.state.InfectionState;
import de.belmega.biohazard.server.persistence.state.WorldState;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.inject.Inject;
import java.util.*;

/**
 * @author tbelmega on 04.12.2016.
 */
@ManagedBean
@SessionScoped
public class WorldDetailsBean {
    @Inject
    WorldDAO worldDAO;
    private WorldSimulationEntity worldSimulationEntity;
    private long worldId;
    private WorldRunStatus status = WorldRunStatus.STOPPED;

    private World world;

    public void loadWorldEntity() {
        worldSimulationEntity = worldDAO.findWorld(worldId);
    }

    public long getWorldId() {
        return worldId;
    }

    public void setWorldId(long worldId) {
        this.worldId = worldId;
    }

    public WorldSimulationEntity getWorldSimulationEntity() {
        return worldSimulationEntity;
    }

    public void setWorldSimulationEntity(WorldSimulationEntity worldSimulationEntity) {
        this.worldSimulationEntity = worldSimulationEntity;
    }

    public String destroyWorldEntity() {
        worldDAO.destroyWorld(worldSimulationEntity);
        return "index";
    }

    public List<ContinentState> getContinents() {
        WorldState worldState = worldSimulationEntity.getWorldState();
        Set<ContinentState> continents = worldState.getContinents();
        List<ContinentState> continentList = new ArrayList<>(continents);
        Collections.sort(continentList);
        return continentList;
    }

    public Long getTotalPopulation() {
        long totalPopulation = 0;
        for (ContinentState c : getContinents())
            for (CountryState country : c.getCountries())
                totalPopulation += country.getPopulation();

        return totalPopulation;
    }

    public List<String> getDiseaseNames() {
        Set<String> diseaseNames = new HashSet<>();
        for (ContinentState continent : worldSimulationEntity.getWorldState().getContinents())
            for (CountryState c : continent.getCountries())
                for (InfectionState i : c.getInfectedPeoplePerDisease())
                    diseaseNames.add(i.getDiseaseName());

        List<String> diseaseNameList = new ArrayList<>(diseaseNames);
        Collections.sort(diseaseNameList);
        return diseaseNameList;
    }

    public Map<String, Long> getWorldInfectionState() {
        Map<String, Long> infections = new HashMap<>();

        for (ContinentState continent : worldSimulationEntity.getWorldState().getContinents())
            for (CountryState c : continent.getCountries())
                for (InfectionState i : c.getInfectedPeoplePerDisease())
                    if (infections.containsKey(i.getDiseaseName()))
                        infections.put(i.getDiseaseName(), infections.get(i.getDiseaseName()) + i.getAmount());
                    else
                        infections.put(i.getDiseaseName(), i.getAmount());

        return infections;
    }

    public WorldRunStatus getStatus() {
        return status;
    }

    public String getBtnRunValue() {
        if (status.equals(WorldRunStatus.RUNNING))
            return "Stop";
        else
            return "Run";
    }

    public String btnRunClick() {
        if (status.equals(WorldRunStatus.RUNNING))
            stopWorld();
        else
            startWorld();

        return "worlddetails.xhtml?worldId=" + worldId;
    }

    private void startWorld() {
        this.world = worldSimulationEntity.getWorldState().build();
        world.run(1000);

        status = WorldRunStatus.RUNNING;
    }

    private void stopWorld() {
        world.stop();
        worldSimulationEntity.setWorldState(world.getState());
        worldDAO.saveWorld(worldSimulationEntity);

        status = WorldRunStatus.STOPPED;
    }

    public long getAge() {
        return worldSimulationEntity.getWorldState().getAge();
    }

    public String btnTickClick() {
        world = worldSimulationEntity.getWorldState().build();

        world.tick();

        worldSimulationEntity.setWorldState(world.getState());
        worldDAO.saveWorld(worldSimulationEntity);

        return "worlddetails.xhtml?worldId=" + worldId;
    }

    public boolean isRunning() {
        return status.equals(WorldRunStatus.RUNNING);
    }
}

server/src/main/java/de/belmega/biohazard/server/jsf/WorldListBean.java
package de.belmega.biohazard.server.jsf;

import de.belmega.biohazard.server.ejb.WorldDAO;
import de.belmega.biohazard.server.persistence.entities.WorldSimulationEntity;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.inject.Inject;
import java.util.List;

/**
 * @author tbelmega on 03.12.2016.
 */
@ManagedBean
@RequestScoped
public class WorldListBean {
    @Inject
    WorldDAO worldDAO;
    private List<WorldSimulationEntity> worlds;
    private String filter;
    private boolean orderAscending = true;

    public List<WorldSimulationEntity> getWorlds() {
        if (worlds == null) {
            worlds = worldDAO.listWorlds(filter, orderAscending);
        }
        return worlds;
    }

    public boolean isOrderAscending() {
        return orderAscending;
    }

    public void setOrderAscending(boolean orderAscending) {
        this.orderAscending = orderAscending;
    }

    public String getFilter() {
        return filter;
    }

    public void setFilter(String filter) {
        this.filter = filter;
        this.worlds = null;
    }
}

server/src/main/webapp/countrydetails.xhtml
<ui:composition
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:h="http://xmlns.jcp.org/jsf/html"
        template="template.xhtml">

    <ui:define name="content">
        <f:metadata>
            <!-- When page is loaded, get ID from URL and store it in the bean.
             Then call loadCountry, to let the bean load the entity. -->
            <f:viewParam name="countryId" value="#{countryDetailsBean.countryId}"/>
            <f:event type="preRenderComponent" listener="#{countryDetailsBean.loadCountry()}"/>
        </f:metadata>

        <h:form>
            <h1>#{countryDetailsBean.country.name}</h1>

            <h:panelGrid columns="2">
                <h:outputLabel>Population: </h:outputLabel>
                <h:outputText value="#{countryDetailsBean.country.population}">
                    <f:convertNumber groupingUsed="true"/>
                </h:outputText>
                <h:outputLabel>Deceased Population: </h:outputLabel>
                <h:outputText value="#{countryDetailsBean.country.deceasedPopulation}">
                    <f:convertNumber groupingUsed="true"/>
                </h:outputText>
                <h:outputLabel>Growth per tick: </h:outputLabel>
                <h:outputText value="#{countryDetailsBean.country.growthFactor}">
                    <f:convertNumber type="percent" minFractionDigits="2"/>
                </h:outputText>
            </h:panelGrid>

            <h2>Diseases: </h2>
            <h:dataTable value="#{countryDetailsBean.country.infectedPeoplePerDisease}" var="infection">
                <h:column>
                    #{infection.diseaseName}
                </h:column>
                <h:column>
                    <h:outputText value="#{infection.amount}">
                        <f:convertNumber groupingUsed="true"/>
                    </h:outputText>
                </h:column>
            </h:dataTable>
        </h:form>
    </ui:define>

</ui:composition>

server/src/main/webapp/createworld.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://java.sun.com/jsf/html"
        template="template.xhtml">
    <ui:define name="content">

        <h:form>
            <h1>Create new world</h1>
            <h:outputLabel>Name: </h:outputLabel>
            <h:inputText id="nameInput" value="#{createWorldBean.worldSimulationEntity.name}"/>

            <div>
                <h:commandButton id="btnOK" value="Create" action="#{createWorldBean.submit}"/>
                <h:commandButton id="btnAbort" value="Cancel" action="#{createWorldBean.destroyWorldEntity}"/>
            </div>
        </h:form>
    </ui:define>
</ui:composition>

server/src/main/webapp/index.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:f="http://java.sun.com/jsf/core"
        template="template.xhtml">
    <ui:define name="content">
        <f:metadata>
            <f:viewParam name="order" value="#{worldListBean.orderAscending}"></f:viewParam>
        </f:metadata>
        <h:form>

            <h:inputText value="#{worldListBean.filter}"/>
            <h:commandButton value="Filter"/>
            <h:dataTable value="#{worldListBean.worlds}" var="world">
                <h:column>
                    <f:facet name="header">Name</f:facet>
                    <h:link value="#{world.name}" outcome="worlddetails.xhtml">
                        <f:param name="worldId" value="#{world.id}"/>
                    </h:link>
                </h:column>

                <h:column>
                    <f:facet name="header">
                        <h:link value="Created">
                            <!-- Link to same page, with new value as URL parameter -->
                            <f:param name="order" value="#{!worldListBean.orderAscending}"/>
                        </h:link>
                    </f:facet>
                    <h:outputText value="#{world.creationDate}">
                        <f:convertDateTime pattern="dd.MM.yyyy HH:mm"/>
                    </h:outputText>
                </h:column>
            </h:dataTable>
            <h:commandButton id="btnCreateWorld" value="Create World" action="createworld"/>
        </h:form>

    </ui:define>
</ui:composition>

server/src/main/webapp/printreport.xhtml
<ui:composition
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:h="http://xmlns.jcp.org/jsf/html"
        template="template.xhtml">

    <ui:define name="content">
        <f:metadata>
            <!-- When page is loaded, get ID from URL and store it in the bean. -->
            <f:viewParam name="worldId" value="#{printWorldReportBean.worldId}"/>
        </f:metadata>

        <h:form>
            <h:commandButton id="btnPrint"
                             value="Get report as PDF"
                             actionListener="#{printWorldReportBean.btnPrintClick}"
            />
        </h:form>

    </ui:define>

</ui:composition>

server/src/main/webapp/template.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
>


<h:head>
    <title>Biohazard</title>
    <h:outputStylesheet name="css/screen.css"/>
</h:head>

<h:body>
    <div id="page">
        <div id="container" class="shadowed">
            <div id="header">
                <span>Biohazard World Monitor</span>
            </div>
            <div id="content">
                <ui:insert name="content">
                    [Content will be inserted here]
                </ui:insert>
            </div>
            <div id="footer">
                <span>1.0</span>
            </div>
        </div>
    </div>
</h:body>
</html>

server/src/main/webapp/worlddetails.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:f="http://java.sun.com/jsf/core"
        template="template.xhtml">
    <ui:define name="content">
        <f:metadata>
            <!-- When page is loaded, get ID from URL and store it in the bean.
             Then call loadWorldEntity, to let the bean load the entity. -->
            <f:viewParam name="worldId" value="#{worldDetailsBean.worldId}"/>
            <f:event type="preRenderComponent" listener="#{worldDetailsBean.loadWorldEntity}"/>
        </f:metadata>

        <h:form>
            <h1>#{worldDetailsBean.worldSimulationEntity.name}</h1>

            <h:panelGrid columns="2">
                <h:outputLabel>Export: </h:outputLabel>
                <h:link value="Print report" outcome="printreport.xhtml">
                    <f:param name="worldId" value="#{worldDetailsBean.worldId}"/>
                </h:link>

                <h:outputLabel>Created: </h:outputLabel>
                <h:outputText value="#{worldDetailsBean.worldSimulationEntity.creationDate}">
                    <f:convertDateTime pattern="dd.MM.yyyy HH:mm"/>
                </h:outputText>

            </h:panelGrid>
            <h:panelGrid columns="2">
                <h:outputLabel>Age: </h:outputLabel>
                <h:outputText value="#{worldDetailsBean.age} Ticks">
                    <f:convertNumber groupingUsed="true"/>
                </h:outputText>
                <h:outputLabel>Population: </h:outputLabel>
                <h:outputText value="#{worldDetailsBean.totalPopulation}">
                    <f:convertNumber groupingUsed="true"/>
                </h:outputText>
            </h:panelGrid>

            <h:dataTable id="continentTable"
                         value="#{worldDetailsBean.continents}"
                         var="continent">
                <h:column>
                    #{continent.name}
                </h:column>
                <h:column>
                    <h:dataTable value="#{continent.sortedCountries}" var="country">
                        <h:column>
                            <h:link value="#{country.name}" outcome="countrydetails.xhtml">
                                <f:param name="countryId" value="#{country.id}"/>
                            </h:link>
                        </h:column>
                        <h:column>
                            <h:outputText value="#{country.population}">
                                <f:convertNumber groupingUsed="true"/>
                            </h:outputText>
                        </h:column>
                    </h:dataTable>
                </h:column>
            </h:dataTable>

            <h:outputLabel>Diseases: </h:outputLabel>
            <h:dataTable value="#{worldDetailsBean.worldInfectionState.entrySet()}" var="infection">
                <h:column>
                    #{infection.key}
                </h:column>
                <h:column>
                    <h:outputText value="#{infection.value}">
                        <f:convertNumber groupingUsed="true"/>
                    </h:outputText>
                </h:column>
            </h:dataTable>

            <h:panelGrid columns="4">
                <h:outputLabel>Status:</h:outputLabel>
                #{worldDetailsBean.status}
                <h:commandButton id="btnRun"
                                 value="#{worldDetailsBean.btnRunValue}"
                                 action="#{worldDetailsBean.btnRunClick}"
                                 rerender="continentTable"
                />
                <h:commandButton id="btnTick"
                                 value="Tick"
                                 disabled="#{worldDetailsBean.running}"
                                 action="#{worldDetailsBean.btnTickClick}"
                                 rerender="continentTable"
                />
            </h:panelGrid>


            <div>
                <h:commandButton id="btnBack" value="Back" action="index"/>
                <h:commandButton id="btnDelete" value="Delete"
                                 onclick="if (! confirm('Destroy this world?')) return false"
                                 action="#{worldDetailsBean.destroyWorldEntity}"/>
            </div>
        </h:form>

    </ui:define>
</ui:composition>